stages:
- builld
- publish
build:
  stage: build
  image:
    name: golang:1.13.1
  script:
  - go build -o main main.go
  artifacts:
    paths:
    - main
  variables:
    cgoenabled: 0
publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
  script:
  - echo "{"auths":{"$CI_REGISTRY":{"username":"$CI_REGISTRY_USER","password":"$CI_REGISTRY_PASSWORD"}}}" > /kaniko/.docker/config.json
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  dependencies:
  - build
  only:
  - master
deploy:
  stage: deploy
  image:
    name: alpine:3.8
  beforescript:
  - apk add --no-cache git curl bash
  - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
  - mv kustomize /usr/local/bin/
  - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@
  - git config --global user.email "gitlab@gitlab.com"
  - git config --global user.name "GitLab CI/CD"
  script:
  - git checkout -B master
  - cd manifests/
  - kustomize edit set image $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  - cat kustomization.yaml
  - git commit -am '[skip ci] DEV image update'
  - git push origin master
  only:
  - master
